name: Workflow Test on Publish
on:
  release:
    types:
      - published
  pull_request:

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "never"
          do_not_skip: '["workflow_dispatch", "schedule"]'
  run-tests:
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    needs: pre_job
    uses: ./.github/workflows/workflow-call-test.yml
  fake-build:
    name: Fake Build
    needs: run-tests
    if: |
      always() &&
      (needs.run-tests.result == 'success' || needs.run-tests.result == 'skipped') &&
      github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Fake Build
        run: echo "fake build!"
  fake-publish:
    name: Fake Build
    needs: fake-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Fake Post Build
        run: echo "fake post build!"
